### ISSUE TITLE
User Data Vulnerability

### ISSUE THREAD

**Issue by rathlinus** [Aravin/Resume-Vita#8]
I've stumbled upon a potential security issue with your site. The XML files that are stored on AWS used for CV-making are open and contain sensitive user info like names, emails, phone numbers, etc. These could be scraped and misused.

I will not share the url publicly, but i can email it.

**Comment by rathlinus** [comment]
Email is sent

**Comment by Aravin** [comment]
Email not received. Checked spam too.

**Comment by rathlinus** [comment]
Typo in the email adresse. Check now

**Comment by Aravin** [comment]
Great @rathlinus 

I found that there was some permission issue in AWS S3 bucket. 

I have removed the directory listing permission.

**Comment by Aravin** [comment]
Closing the bug since it is fixed.

Thanks to @rathlinus
